# Generated by Django 4.2.4 on 2023-09-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='emali',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='myprofile',
            old_name='father_name',
            new_name='fathername',
        ),
        migrations.RenameField(
            model_name='myprofile',
            old_name='mother_name',
            new_name='mothername',
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
